# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2985ee113ec63c87eece6c50510423f341c85ee6cc0aef4cccba59fa220af5becdc91b76ed7edced60bf05cdeb84c8cf048a0f89f3e998531216ee53b62faad6

test:
  secret_key_base: dc68ecac7eb6e00f52b54f436ca29cff268ad3609e474989a399a96704d745fe3a996438fb2a41498d2e693e45216c89bc1ffb0696076ab6ef01dd273c6d0927

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
