# Site settings
title: "St. Peter's Monastery - Harrison, MT"
email: stpetersmonastery@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  St. Peter’s Monastery is ideally situated not only to offer a sequestered life for monastics, but also to support the growth of the Church in Montana and throughout the Mountain West.  On the one hand, the ranch is surrounded by mountains in sparsely-populated ranchlands and lies off the grid, generating its own electricity from wind and sun.  Philosophy River, named by explorers Lewis and Clark in 1805, flows through the property which also forms the north shore of an undeveloped lake roughly six miles long.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stpetersmonastery.github.io" # deployment
# url: "http://localhost:4000" # development

twitter_username: stpetersmonastery
github_username:  stpetersmonastery

# Build settings
markdown: kramdown
